K_topk: 48
batch_size: 64
dataset:
  captions_json: /content/data/coco/annotations/captions_val2017.json
  image_dir: /content/data/coco/val2017
  max_samples: 500
  name: coco_captions
  split: validation
eps_grid:
- 0.05
- 0.1
- 0.2
h_grid:
- 0.3
- 0.5
- 0.8
- 1.2
inherit: default.yaml
task: vision_text
tau_grid:
- 0.6
- 0.8
- 1.0
- 1.3
- 1.6
temperature_grid:
- 0.7
- 0.9
- 1.1
- 1.3
