inherit: default.yaml
# search grids (tighter, theory-informed)
temperature_grid: [0.7, 0.9, 1.1, 1.3]
tau_grid:         [0.6, 0.8, 1.0, 1.3, 1.6]
eps_grid:         [0.05, 0.1, 0.2]
h_grid:           [0.3, 0.5, 0.8, 1.2]
K_topk:           48
batch_size:       64
dataset:
  name: "poloclub/pope"  # tiny but public; fallback to synthetic if missing
  split: "validation"
  max_samples: 500
  captions_csv: /content/data/audiocaps/val.csv      # CSV with (ytid,start_time,caption) is fine
  audio_dir: /content/data/audiocaps/wavs            # optional if in case of audio files
task: "vision_text_bias"
