K_topk: 48
batch_size: 64
dataset:
  annotations_json: /content/data/vqa2/v2_mscoco_val2014_annotations.json
  image_dir: /content/data/vqa2/val2014
  max_samples: 500
  name: HuggingFaceM4/VQAv2
  questions_json: /content/data/vqa2/v2_OpenEnded_mscoco_val2014_questions.json
  split: validation
eps_grid:
- 0.05
- 0.1
- 0.2
h_grid:
- 0.3
- 0.5
- 0.8
- 1.2
inherit: default.yaml
task: vision_text_qa
tau_grid:
- 0.6
- 0.8
- 1.0
- 1.3
- 1.6
temperature_grid:
- 0.7
- 0.9
- 1.1
- 1.3
